package io.github.capitan0n.droynis.report

import io.github.capitan0n.droynis.core.Category
import io.github.capitan0n.droynis.core.Finding
import io.github.capitan0n.droynis.core.ScanContext
import java.time.format.DateTimeFormatter

/**
 * Human-readable report. It contains what the scan observed and the device facts passed in, and
 * nothing else: no hardware identifiers, phone numbers or account names are ever collected.
 */
object MarkdownReport {

    private val TIME = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm z")

    fun render(
        context: ScanContext,
        findings: List<Finding>,
        index: HardeningIndex,
        facts: List<DeviceFact>,
        appVersion: String,
    ): String = buildString {
        appendLine("# Droynis security report")
        appendLine()
        appendLine("- Scanned: ${context.startedAt.format(TIME)}")
        appendLine("- Hardening index: ${scoreLine(index)}")
        val counts = findings.countByVerdict()
        appendLine(
            "- Checks: ${findings.size} · " +
                Verdict.entries.joinToString(" · ") { "${it.symbol} ${it.label.lowercase()} ${counts[it] ?: 0}" },
        )
        appendLine("- Generated by Droynis $appVersion (privilege tier ${context.capabilities.tier})")
        appendLine()

        if (facts.isNotEmpty()) {
            appendLine("## Device")
            appendLine()
            appendLine("| Field | Value |")
            appendLine("|---|---|")
            facts.forEach { appendLine("| ${cell(it.label)} | ${cell(it.value)} |") }
            appendLine()
        }

        for (category in Category.entries) {
            val inCategory = findings.filter { it.spec.category == category }
            if (inCategory.isEmpty()) continue
            appendLine("## ${category.label}")
            appendLine()
            inCategory.forEach { appendFinding(it) }
        }
    }.trimEnd() + "\n"

    private fun scoreLine(index: HardeningIndex): String {
        val score = index.score ?: return "not available (no check could be scored)"
        val grade = index.grade?.let { " (grade ${it.name}, ${it.label.lowercase()})" }.orEmpty()
        val cap = if (index.cappedBy.isEmpty()) {
            ""
        } else {
            ", capped by ${index.cappedBy.joinToString()} (${index.uncappedScore} without the cap)"
        }
        return "$score / 100$grade$cap"
    }

    private fun StringBuilder.appendFinding(finding: Finding) {
        val verdict = finding.verdict
        appendLine("### ${verdict.symbol} ${finding.spec.title} (${finding.spec.id})")
        appendLine()
        appendLine("**${verdict.label}**, severity ${finding.severity.name.lowercase()}: ${finding.summary}")
        appendLine()
        finding.evidence.forEach { item ->
            val value = item.value ?: "n/a"
            val note = item.note?.let { " ($it)" }.orEmpty()
            appendLine("- ${item.label}: `$value`$note, via ${item.source}")
        }
        if (verdict == Verdict.CRITICAL || verdict == Verdict.ATTENTION) {
            appendLine("- What to do: ${finding.spec.remediation.text}")
        }
        appendLine()
    }

    private fun cell(text: String) = text.replace("|", "\\|")
}
