package io.github.capitan0n.droynis.checks.base

import io.github.capitan0n.droynis.core.Category
import io.github.capitan0n.droynis.core.Check
import io.github.capitan0n.droynis.core.CheckSpec
import io.github.capitan0n.droynis.core.Evidence
import io.github.capitan0n.droynis.core.Outcome
import io.github.capitan0n.droynis.core.Reading
import io.github.capitan0n.droynis.core.Remediation
import io.github.capitan0n.droynis.core.ScanContext
import io.github.capitan0n.droynis.core.Severity
import io.github.capitan0n.droynis.core.toEvidence
import kotlin.time.Duration.Companion.seconds

class BootloaderCheck(
    private val attestation: AttestationProbe,
    private val properties: SystemProperties,
) : Check {

    override val spec = CheckSpec(
        id = "INTG-1040",
        category = Category.DEVICE_INTEGRITY,
        title = "Bootloader lock",
        severity = Severity.CRITICAL,
        explanation = "A locked bootloader starts only an operating system signed by the phone's vendor, or " +
            "by a relockable OS such as GrapheneOS. Unlocked, anyone holding the phone can boot a modified " +
            "system that captures your PIN or your data the next time you unlock it, and verified boot no " +
            "longer stops persistent malware.",
        remediation = Remediation(
            text = "Relock the bootloader only if the installed OS supports it: stock firmware, or an OS with " +
                "its own verified-boot key such as GrapheneOS or CalyxOS. Relocking wipes the phone, and " +
                "relocking with an unsupported custom OS can leave it unbootable. With the phone in fastboot " +
                "mode, run this from a computer:",
            command = "fastboot flashing lock",
        ),
        // Generating an attested key in secure hardware can take a few seconds.
        timeout = 20.seconds,
    )

    override suspend fun run(context: ScanContext): Outcome {
        val attested = attestation.attest()
        val props = properties.all()
        val evidence = attestationEvidence(attested) + bootPropertyEvidence(props)

        // A software-only attestation is generated by the OS being judged, so it proves nothing.
        val hardware = (attested as? Reading.Value)?.value?.takeIf { it.securityLevel != SecurityLevel.SOFTWARE }
        val root = hardware?.rootOfTrust
        if (root != null) {
            return when {
                !root.deviceLocked ->
                    Outcome.fail("The bootloader is unlocked (hardware-attested)", evidence)
                root.verifiedBootState == VerifiedBootState.VERIFIED ->
                    Outcome.pass("The bootloader is locked and verified boot passed (hardware-attested)", evidence)
                root.verifiedBootState == VerifiedBootState.SELF_SIGNED ->
                    Outcome.pass("The bootloader is locked with a custom OS key (hardware-attested)", evidence)
                else -> Outcome.fail("Verified boot is ${root.verifiedBootState.label}", evidence)
            }
        }

        // Fallback: boot properties. Root can fake "locked" here, but "unlocked" is reported honestly.
        val values = (props as? Reading.Value)?.value.orEmpty()
        val flashLocked = values[FLASH_LOCKED]
        val deviceState = values[DEVICE_STATE]
        val bootState = values[VERIFIED_BOOT_STATE]
        val lockedByProps = flashLocked == "1" || deviceState == "locked"
        return when {
            flashLocked == "0" || deviceState == "unlocked" || bootState == "orange" ->
                Outcome.fail("The bootloader is unlocked (reported by boot properties)", evidence)
            bootState == "red" -> Outcome.fail("Verified boot failed (reported by boot properties)", evidence)
            lockedByProps && (bootState == "green" || bootState == "yellow") ->
                Outcome.pass("The bootloader is locked (reported by boot properties, not hardware-attested)", evidence)
            else -> Outcome.unknown("The bootloader state could not be determined", evidence)
        }
    }

    private fun attestationEvidence(attested: Reading<KeyAttestation>): List<Evidence> {
        val value = (attested as? Reading.Value)?.value ?: return listOf(attested.toEvidence("Key attestation"))
        val source = attested.source
        val note = "chain not checked against Google's roots, so a compromised OS could forge it"
        return listOfNotNull(
            Evidence(
                "Attestation security level",
                value.securityLevel.name.lowercase(),
                source,
                note = if (value.securityLevel == SecurityLevel.SOFTWARE) "software attestation is not trusted" else null,
            ),
            value.rootOfTrust?.let { Evidence("Device locked (attested)", it.deviceLocked.toString(), source, note) },
            value.rootOfTrust?.let { Evidence("Verified boot state (attested)", it.verifiedBootState.label, source) },
            value.osPatchLevel?.let { Evidence("OS patch level (attested)", formatPatchLevel(it), source) },
        )
    }

    private fun bootPropertyEvidence(props: Reading<Map<String, String>>): List<Evidence> {
        val values = (props as? Reading.Value)?.value ?: return listOf(props.toEvidence("Boot properties"))
        return BOOT_PROPERTIES.map { key -> Evidence(key, values[key] ?: "(not readable)", props.source) }
    }

    private fun formatPatchLevel(yyyymm: Int): String = "%04d-%02d".format(yyyymm / 100, yyyymm % 100)

    companion object {
        const val FLASH_LOCKED = "ro.boot.flash.locked"
        const val DEVICE_STATE = "ro.boot.vbmeta.device_state"
        const val VERIFIED_BOOT_STATE = "ro.boot.verifiedbootstate"
        val BOOT_PROPERTIES = listOf(FLASH_LOCKED, DEVICE_STATE, VERIFIED_BOOT_STATE)
    }
}
